valegas/valegas/core/urls.py
from django.conf.urls import include, url
from valegas.core.views import home

urlpatterns = [
    url(r'^$', home, name='home'),
]

valegas/valegas/produtos/urls.py
from django.conf.urls import include, url
from valegas.produtos.views import lista_produtos, novo_produto, editar_produto, lista_categorias, nova_categoria, editar_categoria

urlpatterns = [
	url(r'^lista-produtos/$', lista_produtos, name='lista_produtos'),
	url(r'^lista-categorias/$', lista_categorias, name='lista_categorias'),
	url(r'^novo-produto/$', novo_produto, name='novo_produto'),
	url(r'^editar-produto/(?P<id>\d+)$', editar_produto, name='editar_produto'),
	url(r'^nova-categoria/$', nova_categoria, name='nova_categoria'),
	url(r'^editar-categoria/(?P<id>\d+)$', editar_categoria, name='editar_categoria'),
]

valegas/valegas/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from valegas.core import urls as core_urls
from valegas.clientes import urls as clientes_urls
from valegas.produtos import urls as produtos_urls

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'', include(core_urls, namespace='core')),
	url(r'^clientes/', include(clientes_urls, namespace='clientes')),
	url(r'^produtos/', include(produtos_urls, namespace='produtos')),
]

valegas/valegas/produtos/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
	nome = models.CharField(max_length=100)

	def __str__(self):
		return self.nome


class Produto(models.Model):
	IS_PROMOCAO_CHOICES = (('N', 'NÃO'),('S', 'SIM'),)
	descricao_simples = models.CharField(u'Descrição Reduzida',max_length=255)
	descricao_completa = models.CharField(u'Descrição Completa', max_length=255)
	resumo 			  = models.CharField(u'Resumo', max_length=255)
	valor_compra      = models.DecimalField(u'valor de compra R$', max_digits=5, decimal_places=2, help_text='Volor que foi comprado.');
	valor_venda       = models.DecimalField(u'valor de venda R$', max_digits=5, decimal_places=2, help_text='Volor que será vendido.');
	categoria         = models.ForeignKey(Categoria)
	estoque           = models.IntegerField()
	#foto              = models.ImageField(upload_to="images/prodthumbs/")
	is_promocao       = models.CharField(max_length=1, choices=IS_PROMOCAO_CHOICES)
	valor_promocao    = models.DecimalField(u'valor promocional R$', max_digits=5, decimal_places=2, help_text='Volor que será vendido quando for promocional.');

	def __str__(self):
		return self.descricao_simples

	def get_preco(self):
		if self.is_promocao == 'N':
			return self.valor_venda
		else:
			return self.valor_promocao

valegas/valegas/produtos/forms.py
from django import forms
from valegas.produtos.models import Produto, Categoria

class ProdutoForm(forms.ModelForm):
	class Meta:
		model = Produto
		fields = ('descricao_simples', 'descricao_completa', 'resumo', 'valor_compra', 'valor_venda', 'categoria', 'estoque', 'is_promocao', 'valor_promocao')


class CategoriaForm(forms.ModelForm):
	class Meta:
		model = Categoria
		fields = ('nome',)

valegas/valegas/produtos/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from valegas.produtos.models import Produto, Categoria
from valegas.produtos.forms import ProdutoForm, CategoriaForm

# Create your views here.


def lista_categorias(request):
	categorias = Categoria.objects.all()
	return render(request, 'produtos/lista_categorias.html', {'categorias': categorias})

def lista_produtos(request):
	produtos = Produto.objects.all()
	return render(request, 'produtos/lista_produtos.html', {'produtos': produtos})

def novo_produto(request):
	debug = ''
	if request.method == 'POST':
		debug = 'requição POST'
		form_produto = ProdutoForm(request.POST)
		
		if form_produto.is_valid():
			
			form_produto.save()
			return redirect(reverse('produtos:lista_produtos'))
		else:
			print(form_produto.errors)
	else:
		debug = 'Novo Cadastro'
		form_produto = ProdutoForm()
	return render(request, 'produtos/novo_produto.html', {'form_produto': form_produto, 'debug':debug})

def editar_produto(request, id):
	produto = Produto.objects.get(id=id)
	if request.method == 'POST':
		form_produto = ProdutoForm(request.POST, instance=produto)
		if form_produto.is_valid():
			form_produto.save()
			return redirect(reverse('produtos:lista_produtos'))
		else:
			print(form_produto.errors)
	else:
		form_produto = ProdutoForm(instance=produto)
	return render(request, 'produtos/editar_produto.html', {'form_produto': form_produto})


def nova_categoria(request):	
	if request.method == 'POST':		
		form_categoria = CategoriaForm(request.POST)
		if form_categoria.is_valid():
			form_categoria.save()
			return redirect(reverse('produtos:lista_categorias'))
		else:
			print(form_categoria.errors)
	else:
		form_categoria = CategoriaForm()
	return render(request, 'produtos/manter_categoria.html', {'form_categoria': form_categoria})

def editar_categoria(request, id):
	categoria = Categoria.objects.get(id=id)
	if request.method == 'POST':
		form_categoria = CategoriaForm(request.POST, instance=categoria)
		if form_categoria.is_valid():
			form_categoria.save()
			return redirect(reverse('produtos:lista_categorias'))
		else:
			print(form_categoria.errors)
	else:
		form_categoria = CategoriaForm(instance=categoria)
	return render(request, 'produtos/editar_categoria.html', {'form_categoria': form_categoria})	

valegas/valegas/produtos/templates/produtos/editar_categoria.html
{% load widget_tweaks %}
<!-- Form Modal -->
<div class="modal-content">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 class="modal-title text-center" id="myModalLabel">Editar Categoria de Produtos</h3>
	</div>
	<div class="modal-body">

		<form role="form" action="{% url 'produtos:editar_categoria' form_categoria.id %}" method="POST">
			{% csrf_token %}
			<div class="box-body">

				<div class="form-group">
					<div class="row">
						<div class="col-sm-12">
							<label>Nome da Categoria:</label>
							{{ form_categoria.nome|add_class:"form-control" }}
						</div>
					</div>
				</div>

			</div>

			<div class="box-footer text-right">
				<button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Salvar</button>
				<button type="button" class="btn btn-danger btn-md" data-dismiss="modal"><i class="glyphicon glyphicon-floppy-close"></i> Fechar</button>
			</div>
		</form>

	</div>
	
</div>

valegas/valegas/produtos/templates/produtos/editar_produto.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block conteudo %}

<section class="content-header">
	<h1 class="page-header">Novo Produto</h1>
	<ol class="breadcrumb">
		<li><a href="{% url 'core:home' %}"><i class="fa fa-dashboard"></i> Home</a></li>
		<li><a href="{% url 'produtos:lista_produtos' %}"><i class="fa fa-dashboard"></i> produtos</a></li>
		<li><a href="#"><i class="fa fa-dashboard"></i> novo produto</a></li>
	</ol>
</section>
<!-- Main content -->

<section class="content">
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">Digite os dados do novo produto</h3>
			{{debug}}
		</div>
		<div class="box-body">
			<form role="form" action="" method="POST">
			{% csrf_token %}
				<div class="box-body">
					
					<div class="form-group">
						<div class="row">
							<div class="col-sm-4">
								<label>Categoria:</label>
								{{ form_produto.categoria|add_class:"form-control" }}
							</div>
						</div>
					</div>	

					<div class="form-group">
						<div class="row">
							<div class="col-sm-12">
								<label>Descrição Simples:</label>
								{{ form_produto.descricao_simples|add_class:"form-control" }}
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">
							<div class="col-sm-12">
								<label>Descrição Completa:</label>
								{{ form_produto.descricao_completa|add_class:"form-control" }}
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">
							<div class="col-sm-12">
								<label>Resumo:</label>
								{{ form_produto.resumo|add_class:"form-control" }}
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">
							<div class="col-sm-4">
								<label>Valor compra R$:</label>
								{{ form_produto.valor_compra|add_class:"form-control" }}
							</div>
							<div class="col-sm-4">
								<label>Valor Venda R$</label>
								{{ form_produto.valor_venda|add_class:"form-control" }}
							</div>
							<div class="col-sm-4">
								<label>Estoque:</label>
								{{ form_produto.estoque|add_class:"form-control" }}
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">
							<div class="col-sm-4">
								<label>Está no promoção?:</label>
								{{ form_produto.is_promocao|add_class:"form-control" }}
							</div>
							<div class="col-sm-4">
								<label>Valor promoção R$</label>
								{{ form_produto.valor_promocao|add_class:"form-control" }}
							</div>
						</div>
					</div>

				</div>

				<div class="box-footer">
					<button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Salvar</button>
				</div>
			</form>
		</div><!-- /.box-body -->

	</div><!-- /.box -->

</section><!-- /.content -->
<!-- Default box -->


{% endblock conteudo %}

valegas/valegas/produtos/templates/produtos/lista_categorias.html
{% extends 'base.html' %}

{% block conteudo %}

<section class="content-header">
	<h1 class="page-header">Categorias</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li><a href="#"><i class="fa fa-dashboard"></i> Produtos</a></li>
		<li><span></i> Categorias</span></li>
	</ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="box box-primary">
		<div class="box-header with-border">
			<div class="row">
				<div class="col-sm-6">
					<a href="{% url 'produtos:nova_categoria'%}"
					data-toggle="modal" data-target="#myModal"
					class="btn btn-md btn-primary"> <i
					class="glyphicon glyphicon-plus"></i> Cadastrar 
				</a>
			</div>
			<!-- search form -->
			<div class="col-sm-6">
				<form action="#" method="get">
					<div class="input-group">
						<input type="text" name="q" class="form-control" placeholder="Digite o nome da Categoria">
						<span class="input-group-btn">
							<button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
						</span>
					</div>
				</form>
				<!-- /.search form -->
			</div>
		</div>
	</div>
	<div class="box-body">
		<div class="table-responsive">
			<table class="table table-hover table-striped">
				<thead>
					<tr>
						<th>Código</th>
						<th>Nome</th>
					</tr>
				</thead>
				<tbody>
					{% for cat in categorias%}

					<tr>
						<td>{{cat.id}}</td>
						<td>{{cat.nome}}</td>

						<td>
							<a href="{% url 'produtos:editar_categoria' cat.id %}"
							data-toggle="modal" data-target="#myModal"
							class="btn btn-md"><i class="glyphicon glyphicon-pencil"></i>
						</td>

					</tr>

					{% endfor %}
				</tbody>
			</table>
		</div>
	</div><!-- /.box-body -->
	<div class="box-footer">
		<span class="text-primary">Total de registros: </span>{{categorias.count}}
	</div><!-- /.box-footer-->
</div><!-- /.box -->

</section><!-- /.content -->
<!-- Default box -->
{% endblock conteudo %}

valegas/valegas/produtos/templates/produtos/lista_produtos.html
{% extends 'base.html' %}

{% block conteudo %}

<section class="content-header">
	<h1 class="page-header">Produtos</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li><span></i> Produtos</span></li>
	</ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="box box-primary">
		<div class="box-header with-border">
			<div class="row">
				<div class="col-sm-6">
					<a class="btn btn-primary" href="{% url 'produtos:novo_produto' %}"><i class="glyphicon glyphicon-plus"></i> Cadastrar</a>
				</div>
				<!-- search form -->
				<div class="col-sm-6">
					<form action="#" method="get">
						<div class="input-group">
							<input type="text" name="q" class="form-control" placeholder="Digite a descrição do Produto">
							<span class="input-group-btn">
								<button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
							</span>
						</div>
					</form>
					<!-- /.search form -->
				</div>
			</div>
		</div>
		<div class="box-body">
			<div class="table-responsive">
				<table class="table table-hover table-striped">
					<thead>
						<tr>
							<th>Código</th>
							<th>Descrição</th>
							<th>Valor R$</th>
							<th>Estoque</th>
						</tr>
					</thead>
					<tbody>
						{% for produto in produtos%}

						<tr>
							<td>{{produto.id}}</td>
							<td>{{produto.descricao_completa}}</td>
							<td>{{produto.valor_venda}}</td>
							<td>{{produto.estoque}}</td>
							<td><a href="{% url 'produtos:editar_produto' produto.id %}"><i class="glyphicon glyphicon-pencil"></i></a></td>
						</tr>

						{% endfor %}
					</tbody>
				</table>
			</div>
		</div><!-- /.box-body -->
		<div class="box-footer">
			<span class="text-footer-table">Total de registros: </span>{{produtos.count}}
		</div><!-- /.box-footer-->
	</div><!-- /.box -->

</section><!-- /.content -->
<!-- Default box -->
{% endblock conteudo %}

valegas/valegas/produtos/templates/produtos/manter_categoria.html
{% load widget_tweaks %}
<!-- Form Modal -->
<div class="modal-content">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 class="modal-title text-center" id="myModalLabel">Nova Categoria de Produtos</h3>
	</div>
	<div class="modal-body">

		<form role="form" action="{% url 'produtos:nova_categoria' %}" method="POST">
			{% csrf_token %}
			<div class="box-body">

				<div class="form-group">
					<div class="row">
						<div class="col-sm-12">
							<label>Nome da Categoria:</label>
							{{ form_categoria.nome|add_class:"form-control" }}
						</div>
					</div>
				</div>

			</div>

			<div class="box-footer text-right">
				<button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Salvar</button>
				<button type="button" class="btn btn-danger btn-md" data-dismiss="modal"><i class="glyphicon glyphicon-floppy-close"></i> Fechar</button>
			</div>
		</form>

	</div>
	
</div>

valegas/valegas/produtos/templates/produtos/novo_produto.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block conteudo %}

<section class="content-header">
	<h1 class="page-header">Novo Produto</h1>
	<ol class="breadcrumb">
		<li><a href="{% url 'core:home' %}"><i class="fa fa-dashboard"></i> Home</a></li>
		<li><a href="{% url 'produtos:lista_produtos' %}"><i class="fa fa-dashboard"></i> produtos</a></li>
		<li><a href="#"><i class="fa fa-dashboard"></i> novo produto</a></li>
	</ol>
</section>
<!-- Main content -->

<section class="content">
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">Digite os dados do novo produto</h3>
		</div>
		<div class="box-body">
			<form role="form" action="" method="POST">
				{% csrf_token %}
				<div class="box-body">
					
					<div class="form-group">
						<div class="row">
							<div class="col-sm-4">
								<label>Categoria:</label>
								{{ form_produto.categoria|add_class:"form-control" }}
							</div>
							<div class="col-sm-1">
								<label>&nbsp;</label>
								<a href="{% url 'produtos:nova_categoria' %}"
								data-toggle="modal" data-target="#myModal"
								class="btn btn-md btn-primary form-control"> <i
								class="glyphicon glyphicon-plus"></i> 
							</a>
						</div>
					</div>
				</div>	

				<div class="form-group">
					<div class="row">
						<div class="col-sm-12">
							<label>Descrição Simples:</label>
							{{ form_produto.descricao_simples|add_class:"form-control" }}
						</div>
					</div>
				</div>

				<div class="form-group">
					<div class="row">
						<div class="col-sm-12">
							<label>Descrição Completa:</label>
							{{ form_produto.descricao_completa|add_class:"form-control" }}
						</div>
					</div>
				</div>

				<div class="form-group">
					<div class="row">
						<div class="col-sm-12">
							<label>Resumo:</label>
							{{ form_produto.resumo|add_class:"form-control" }}
						</div>
					</div>
				</div>

				<div class="form-group">
					<div class="row">
						<div class="col-sm-4">
							<label>Valor compra R$:</label>
							{{ form_produto.valor_compra|add_class:"form-control" }}
						</div>
						<div class="col-sm-4">
							<label>Valor Venda R$</label>
							{{ form_produto.valor_venda|add_class:"form-control" }}
						</div>
						<div class="col-sm-4">
							<label>Estoque:</label>
							{{ form_produto.estoque|add_class:"form-control" }}
						</div>
					</div>
				</div>

				<div class="form-group">
					<div class="row">
						<div class="col-sm-4">
							<label>Está no promoção?:</label>
							{{ form_produto.is_promocao|add_class:"form-control" }}
						</div>
						<div class="col-sm-4">
							<label>Valor promoção R$</label>
							{{ form_produto.valor_promocao|add_class:"form-control" }}
						</div>
					</div>
				</div>

			</div>

			<div class="box-footer">
				<button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Salvar</button>
			</div>
		</form>
	</div><!-- /.box-body -->

</div><!-- /.box -->

</section><!-- /.content -->
<!-- Default box -->


{% endblock conteudo %}