valegas/valegas/clientes/urls.py
from django.conf.urls import include, url
from valegas.clientes.views import lista_clientes, novo_cliente, editar_cliente, novo_bairro

urlpatterns = [
	url(r'^lista-cliente/$', lista_clientes, name='lista_clientes'),
	url(r'^novo-cliente/$', novo_cliente, name='novo_cliente'),
	url(r'^editar-cliente/(?P<id>\d+)$', editar_cliente, name='editar_cliente'),
	url(r'^novo-bairro/$', novo_bairro, name='novo_bairro'),
]

valegas/valegas/core/urls.py
from django.conf.urls import include, url
from valegas.core.views import home

urlpatterns = [
    url(r'^$', home, name='home'),
]

valegas/valegas/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from valegas.core import urls as core_urls
from valegas.clientes import urls as clientes_urls
from valegas.produtos import urls as produtos_urls

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'', include(core_urls, namespace='core')),
	url(r'^clientes/', include(clientes_urls, namespace='clientes')),
	url(r'^produtos/', include(produtos_urls, namespace='produtos')),
]

valegas/valegas/clientes/models.py
from django.db import models

# Create your models here.

class Bairro(models.Model):
	nome_bairro   = models.CharField(max_length=100)
	cidade = models.CharField(max_length=100)
	
	ESTADO_CHOICES = (
	    ('AC', 'Acre'), 
	    ('AL', 'Alagoas'),
	    ('AP', 'Amapá'),
	    ('BA', 'Bahia'),
	    ('CE', 'Ceará'),
	    ('DF', 'Distrito Federal'),
	    ('ES', 'Espírito Santo'),
	    ('GO', 'Goiás'),
	    ('MA', 'Maranão'),
	    ('MG', 'Minas Gerais'),
	    ('MS', 'Mato Grosso do Sul'),
	    ('MT', 'Mato Grosso'),
	    ('PA', 'Pará'),
	    ('PB', 'Paraíba'),
	    ('PE', 'Pernanbuco'),
	    ('PI', 'Piauí'),
	    ('PR', 'Paraná'),
	    ('RJ', 'Rio de Janeiro'),
	    ('RN', 'Rio Grande do Norte'),
	    ('RO', 'Rondônia'),
	    ('RR', 'Roraima'),
	    ('RS', 'Rio Grande do Sul'),
	    ('SC', 'Santa Catarina'),
	    ('SE', 'Sergipe'),
	    ('SP', 'São Paulo'),
	    ('TO', 'Tocantins')
	)
	uf = models.CharField(max_length=2, choices=ESTADO_CHOICES)
	
	def __str__(self):
		return self.nome_bairro

class Cliente(models.Model):
	nome      = models.CharField(max_length=100)
	rg        = models.CharField(max_length=12)
	cpf       = models.CharField(max_length=12)
	fone      = models.CharField(max_length=12)
	logradouro      = models.CharField(max_length=100)
	tipo_logradouro = models.CharField(max_length=50)
	cep       = models.CharField(max_length=12)
	numero    = models.CharField(max_length=12)
	latitude  = models.CharField(max_length=50)
	longtude  = models.CharField(max_length=50)
	ponto_referencia  = models.CharField(max_length=100)
	#bairro    = models.OneToOneField(Bairro)
	bairro = models.ForeignKey(Bairro)



	def __str__(self):
		return self.nome

valegas/valegas/clientes/forms.py
from django import forms
from valegas.clientes.models import Cliente, Bairro

class ClienteForm(forms.ModelForm):
	class Meta:
		model = Cliente
		fields = ('nome',
					'fone',
					'nome',
					'rg',
					'cpf',
					'fone',
					'logradouro',
					'tipo_logradouro',
					'cep',
					'numero',
					'ponto_referencia', 'bairro')



class BairroForm(forms.ModelForm):
	class Meta:
		model = Bairro
		fields = ('nome_bairro','cidade', 'uf')

valegas/valegas/clientes/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from valegas.clientes.models import Cliente, Bairro
from valegas.clientes.forms import ClienteForm, BairroForm

# Create your views here.


def lista_clientes(request):
	clientes = Cliente.objects.all()
	return render(request, 'clientes/lista_clientes.html', {'clientes': clientes})

def novo_cliente(request):
	debug = ''
	if request.method == 'POST':
		form_cliente = ClienteForm(request.POST)
		if form_cliente.is_valid():
			form_cliente.save()

			return redirect(reverse('clientes:lista_clientes'))
		else:
			print(form_cliente.errors)
	else:
		debug = 'Novo Cadastro'
		form_cliente = ClienteForm()
	return render(request, 'clientes/novo_cliente.html', {'form_cliente': form_cliente, 'debug':debug})



def novo_bairro(request):
	if request.method == 'POST':
		form_bairro = BairroForm(request.POST)
		if form_bairro.is_valid():
			form_bairro.save()
			return redirect(reverse('clientes:lista_clientes'))
		else:
			print(form_bairro.errors)
	else:
		form_bairro = BairroForm()
	return render(request, 'clientes/novo_bairro.html', {'form_bairro': form_bairro, 'request': request})

def editar_cliente(request, id):
	cliente = Cliente.objects.get(id=id)
	if request.method == 'POST':
		form_cliente = ClienteForm(request.POST, instance=cliente)
		if form_cliente.is_valid():
			form_cliente.save()
			return redirect(reverse('clientes:lista_clientes'))
		else:
			print(form_cliente.errors)
	else:
		form_cliente = ClienteForm(instance=cliente)
	return render(request, 'clientes/editar_cliente.html', {'form_cliente': form_cliente})

valegas/valegas/clientes/templates/clientes/editar_cliente.html
<!--
<form role="form">
	<div class="box-body">
		<div class="form-group">
			<label for="exampleInputEmail1">Email address</label>
			<input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Password</label>
			<input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
		</div>
		<div class="form-group">
			<label for="exampleInputFile">File input</label>
			<input type="file" id="exampleInputFile">
			<p class="help-block">Example block-level help text here.</p>
		</div>
		<div class="checkbox">
			<label>
				<input type="checkbox"> Check me out
			</label>
		</div>
	</div>

	<div class="box-footer">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>
</form>
-->

{% extends 'base.html' %}
{% load widget_tweaks %}
{% block conteudo %}

<section class="content-header">
	<h1 class="page-header">Novo Cliente</h1>
	<ol class="breadcrumb">
		<li><a href="{% url 'core:home' %}"><i class="fa fa-dashboard"></i> Home</a></li>
		<li><a href="{% url 'clientes:lista_clientes' %}"><i class="fa fa-dashboard"></i> clientes</a></li>
		<li><a href="#"><i class="fa fa-dashboard"></i> novo cliente</a></li>
	</ol>
</section>
<!-- Main content -->

<section class="content">
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">Digite os dados do novo cliente</h3>
		</div>
		<div class="box-body">
			<form role="form" action="" method="POST">
			{% csrf_token %}
				<div class="box-body">
					<div class="form-group">
						<div class="row">

							<div class="col-sm-12">
								<label>Nome Complentos:</label>
								{{ form_cliente.nome|add_class:"form-control" }}
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">

							<div class="col-sm-4">
								<label>Rg:</label>
								{{ form_cliente.rg|add_class:"form-control" }}
							</div>
							<div class="col-sm-4">
								<label>Cpf:</label>
								{{ form_cliente.cpf|add_class:"form-control" }}
							</div>
							<div class="col-sm-4">
								<label>Telefone:</label>
								{{ form_cliente.fone|add_class:"form-control" }}
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">
							<div class="col-sm-3">
								<label>Cep:</label>
								{{ form_cliente.cep|add_class:"form-control" }}
							</div>
							<div class="col-sm-3">
								<label>Logradouro:</label>
								{{ form_cliente.logradouro|add_class:"form-control" }}
							</div>
							<div class="col-sm-3">
								<label>Tipo de Logradouro:</label>
								{{ form_cliente.tipo_logradouro|add_class:"form-control" }}
							</div>
							<div class="col-sm-3">
								<label>Número:</label>
								{{ form_cliente.numero|add_class:"form-control" }}
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">
							<div class="col-sm-6">
								<label>Ponto de Referência:</label>
								{{ form_cliente.ponto_referencia|add_class:"form-control" }}
							</div>
							<div class="col-sm-4">
								<label>Bairro:</label>
								{{ form_cliente.bairro|add_class:"form-control" }}
							</div>
						</div>
					</div>

				</div>

				<div class="box-footer">
					<a href="{% url 'clientes:lista_clientes' %}" class="btn btn-danger">Cancelar</a>
					<button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Salvar</button>
				</div>
			</form>
		</div><!-- /.box-body -->

	</div><!-- /.box -->

</section><!-- /.content -->
<!-- Default box -->


{% endblock conteudo %}

valegas/valegas/clientes/templates/clientes/lista_clientes.html
{% extends 'base.html' %}

{% block conteudo %}

<section class="content-header">
	<h1 class="page-header">Clientes</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li><span></i> Clientes</span></li>
	</ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="box box-primary">
		<div class="box-header with-border">
			<div class="row">
				<div class="col-sm-6">
					<a class="btn btn-primary" href="{% url 'clientes:novo_cliente' %}"><i class="glyphicon glyphicon-plus"></i> Cadastrar</a>
				</div>
				<!-- search form -->
				<div class="col-sm-6">
					<form action="#" method="get">
						<div class="input-group">
							<input type="text" name="q" class="form-control" placeholder="Digite o nome do cliente">
							<span class="input-group-btn">
								<button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
							</span>
						</div>
					</form>
					<!-- /.search form -->
				</div>
			</div>
		</div>
		<div class="box-body">
			<div class="table-responsive">
				<table class="table table-hover table-striped">
					<thead>
						<tr>
							<th>Nome cliente</th>
							<th>Cpf</th>
							<th>Fone</th>
							<th>Endereço</th>
							<th>Ação</th>
						</tr>
					</thead>
					<tbody>
						{% for cliente in clientes%}

						<tr>
							<td>{{cliente.nome}}</td>
							<td>{{cliente.cpf}}</td>
							<td>{{cliente.fone}}</td>
							<td>{{cliente.logradouro}}, {{cliente.numero}}, {{cliente.bairro.nome_bairro}}, {{cliente.bairro.cidade}} - {{cliente.bairro.uf}}</td>
							<td><a href="{% url 'clientes:editar_cliente' cliente.id %}"><i class="glyphicon glyphicon-pencil"></i></a></td>
						</tr>

						{% endfor %}
					</tbody>
				</table>
			</div>
		</div><!-- /.box-body -->
		<div class="box-footer">
			<span>Total de registros: </span>{{clientes.count}}
		</div><!-- /.box-footer-->
	</div><!-- /.box -->

</section><!-- /.content -->
<!-- Default box -->
{% endblock conteudo %}

valegas/valegas/clientes/templates/clientes/novo_bairro.html
{% load widget_tweaks %}
<!-- Form Modal -->

	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3 class="modal-title text-center" id="myModalLabel">Selecione o Imóvel para Locação</h3>
	</div>
	<div class="modal-body">

		<form role="form" action="{% url 'clientes:novo_bairro' %}" method="POST" id="bairro">
			{% csrf_token %}
			<div class="form-group">
				<div class="row">
					<div class="col-sm-12">
						<label>Nome do Bairro:</label>
						{{ form_bairro.nome_bairro|add_class:"form-control" }}
					</div>
				</div>
			</div>

			<div class="form-group">
				<div class="row">
					<div class="col-sm-12">
						<label>Cidade:</label>
						{{ form_bairro.cidade|add_class:"form-control" }}
					</div>
				</div>
			</div>
			
			<div class="form-group">
				<div class="row">
					<div class="col-sm-12">
						<label>Uf:</label>
						{{ form_bairro.uf|add_class:"form-control" }}
					</div>
				</div>
			</div>
			
			<div class="modal-footer">
				<button type="" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk" id="sel_bairro"></i> Salvar</button>
				<button type="button" class="btn btn-danger btn-md" data-dismiss="modal">Fechar</button>
			</div>
		</form>

	</div>
	

valegas/valegas/clientes/templates/clientes/novo_cliente.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block conteudo %}

<section class="content-header">
	<h1 class="page-header">Novo Cliente</h1>
	<ol class="breadcrumb">
		<li><a href="{% url 'core:home' %}"><i class="fa fa-dashboard"></i> Home</a></li>
		<li><a href="{% url 'clientes:lista_clientes' %}"><i class="fa fa-dashboard"></i> clientes</a></li>
		<li><a href="#"><i class="fa fa-dashboard"></i> novo cliente</a></li>
	</ol>
</section>
<!-- Main content -->

<section class="content">
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title">Digite os dados do novo cliente</h3>
			{{debug}}
		</div>
		<div class="box-body">
			<form role="form" action="" method="POST">
				{% csrf_token %}
				<div class="box-body">
					<div class="form-group">
						<div class="row">

							<div class="col-sm-12">
								<label>Nome Complentos:</label>
								{{ form_cliente.nome|add_class:"form-control" }}
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">

							<div class="col-sm-4">
								<label>Rg:</label>
								{{ form_cliente.rg|add_class:"form-control" }}
							</div>
							<div class="col-sm-4">
								<label>Cpf:</label>
								{{ form_cliente.cpf|add_class:"form-control" }}
							</div>
							<div class="col-sm-4">
								<label>Telefone:</label>
								{{ form_cliente.fone|add_class:"form-control" }}
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">
							<div class="col-sm-3">
								<label>Cep:</label>
								{{ form_cliente.cep|add_class:"form-control" }}
							</div>
							<div class="col-sm-3">
								<label>Logradouro:</label>
								{{ form_cliente.logradouro|add_class:"form-control" }}
							</div>
							<div class="col-sm-3">
								<label>Tipo de Logradouro:</label>
								{{ form_cliente.tipo_logradouro|add_class:"form-control" }}
							</div>
							<div class="col-sm-3">
								<label>Número:</label>
								{{ form_cliente.numero|add_class:"form-control" }}
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">
							<div class="col-sm-12">
								<label>Ponto de Referência:</label>
								{{ form_cliente.ponto_referencia|add_class:"form-control" }}
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">
							<div class="col-sm-4">
								<label>Bairro:</label>
								{{ form_cliente.bairro|add_class:"form-control" }}
							</div>
							<div class="col-sm-1">
								<label>&nbsp;</label>
								<a href="{% url 'clientes:novo_bairro' %}"
								data-toggle="modal" data-target="#myModal"
								class="btn btn-md btn-primary form-control"> <i
								class="glyphicon glyphicon-plus"></i> 
							</a>
							</div>
							<div class="col-sm-4">

							</div>
						</div>
					</div>

					<div class="box-footer">
						<button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> Salvar</button>
					</div>
				</form>
			</div><!-- /.box-body -->

		</div><!-- /.box -->

	</section><!-- /.content -->
	<!-- Default box -->


	{% endblock conteudo %}